--- variables are snake_case
--- functions are camelCase
--- classes are PascalCase
--- constants are ALL_CAPS
--- package names are lowercase, short, and without underscores
--- intanced objects modules are camelCase